services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.selfsigned.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/selfsigned:/etc/nginx/ssl:ro
      - ../deploy/html:/deploy/html:ro
    depends_on:
      - godot_server
      - blueos1
      - blueos2
      # - blueos3
      # - blueos4
    networks:
      blueos_network:
        ipv4_address: 192.168.100.20
    restart: unless-stopped

  godot_server:
    image: ubuntu:22.04
    platform: linux/amd64

    volumes:
      - ../deploy:/deploy
    working_dir: /deploy
    command: ./dedicated_server.sh
    networks:
      blueos_network:
        ipv4_address: 192.168.100.30
    restart: unless-stopped
    
  blueos1:
    image: williangalvani/blueos-core:bluesim_dev
    environment:
      - BLUEOS_DISABLE_SERVICES=cable_guy,beacon,kraken,wifi,bridget,commander,nmea_injector,iperf3,versionchooser,ping,log_zipper
      - JSON_SIM_PORT=9002
      - JSON_SIM_HOST=192.168.100.30
    pull_policy: always
    networks:
      blueos_network:
        ipv4_address: 192.168.100.2
    volumes:
      - ./blueos1/eeprom.bin:/root/.config/ardupilot-manager/firmware/eeprom.bin
      - ./blueos1/bag-of-holding:/root/.config/bag-of-holding

  blueos2:
    image: williangalvani/blueos-core:bluesim_dev
    environment:
      - BLUEOS_DISABLE_SERVICES=cable_guy,beacon,kraken,wifi,bridget,commander,nmea_injector,iperf3,versionchooser,ping,log_zipper
      - JSON_SIM_PORT=9003
      - JSON_SIM_HOST=192.168.100.30
    pull_policy: always
    networks:
      blueos_network:
        ipv4_address: 192.168.100.3
    volumes:
      - ./blueos2/eeprom.bin:/root/.config/ardupilot-manager/firmware/eeprom.bin
      - ./blueos2/bag-of-holding:/root/.config/bag-of-holding

  blueos3:
    image: williangalvani/blueos-core:bluesim_dev
    environment:
      - BLUEOS_DISABLE_SERVICES=cable_guy,beacon,kraken,wifi,bridget,commander,nmea_injector,iperf3,versionchooser,ping,log_zipper
      - JSON_SIM_PORT=9004
      - JSON_SIM_HOST=192.168.100.30
    pull_policy: always
    networks:
      blueos_network:
        ipv4_address: 192.168.100.4
    volumes:
      - ./blueos3/eeprom.bin:/root/.config/ardupilot-manager/firmware/eeprom.bin
      - ./blueos3/bag-of-holding:/root/.config/bag-of-holding

  blueos4:
    image: williangalvani/blueos-core:bluesim_dev
    environment:
      - BLUEOS_DISABLE_SERVICES=cable_guy,beacon,kraken,wifi,bridget,commander,nmea_injector,iperf3,versionchooser,ping,log_zipper
      - JSON_SIM_PORT=9005
      - JSON_SIM_HOST=192.168.100.30
    pull_policy: always
    networks:
      blueos_network:
        ipv4_address: 192.168.100.5
    volumes:
      - ./blueos4/eeprom.bin:/root/.config/ardupilot-manager/firmware/eeprom.bin
      - ./blueos4/bag-of-holding:/root/.config/bag-of-holding

networks:
  blueos_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

